import Head from "next/head";

import {
  Navbar,
  Landing,
  HowItWorks,
  Product,
  Efficacy,
  WhyReva,
  Footer,
  Copyright,
} from "../components";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Landing />
        <HowItWorks />
        <div className={styles.bgSection}>
          <Product />
          <Efficacy />
          <WhyReva />
        </div>
        <Footer />
        <Copyright />
      </main>
    </div>
  );
}
