import Head from "next/head";

import {
  Navbar,
  Landing,
  Purpose,
  Product,
  Efficacy,
  WhyReva,
  AboutUs,
  Pillars,
  Gallery,
  Footer,
  Copyright,
} from "../components";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>REVA - The Nutritrap</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Landing />
        <WhyReva />
        {/* <HowItWorks /> */}
        <div className={styles.bgSection}>
          <Product />
          <Efficacy />
          <Gallery />
          <Purpose />
          <Pillars />
        </div>
        <AboutUs />
        <Footer />
        <Copyright />
      </main>
    </div>
  );
}
